source("source.R") # set working directory for the same file location as VB_SEM_MNAR.R
# load("missing_75_n625.RData")

#### Simulate SEM data using sqrtn*sqrtn regular grid.

sqrtn=25 #(i.e.n=sqrtn^2=625)

g<-graph.lattice(c(sqrtn,sqrtn)) #5*4 pixels.

g<-connect.neighborhood(g,1) #connect all vertices by one edge.
#plot(g)
wmat<-as_adjacency_matrix(g) # wmat is a matrix.
w<-mat2listw(wmat,style="W") # w is a listw object.
w=listw2mat(w) # w is a matrix object, but a standardized weight matrix
w=Matrix(w) #convert w into a sparse matrix
# matrix(w,ncol=ncol(w))



p=10
para=sample(1:5,(p+1),replace = T)
para=c(para,c(0.8,sqrt(1)))




sim=simulateSEM(para=para,p=p,weightmat=w)

x=sim$Independent #Leading 1's are generated by this function
x=as.matrix(x,nrow=nrow(w))
y=sim$Dependent
y=as.matrix(y)

### make missing data according to missing value model.

psi=c(1.5,rep(0.5,1),-0.1) #set psi's (changing these values, we can control the missing value %)
nparas<-length(c(para,psi))

splitting=my_splitter_all_xm(x=x,xm=x[,1],y=y,w=w,psi=psi)
m=splitting$m
x=splitting$X
yo=splitting$yo
yu=splitting$yu
w=splitting$W
xm=splitting$xm
mean(m) #This is the missing value %
nu<-sum(m)

#### Obtain theta.start and yu.start  (Obtain starting values for variational means mu)


#---1 starting values for thetas
n<-ncol(w)
no<-n-nu
reg.model<-estimate_regression(x=x,yo=yo,no=no)
reg.model.summary<-summary(reg.model)
sigma2y0<-(reg.model.summary$sigma)^2
beta0<-reg.model.summary$coefficients

prob1<-sum(m)/length(m)

psi0_0<-log(prob1/(1-prob1))
paras.st<-c(as.numeric(beta0[,1]),sigma2y0,0.001,psi0_0,rep(0.1,ncol(xm)+1))

#---2 starting values for yu | starting thetas

wpluswt=(w+t(w))
wtw=t(w)%*%(w)

N1=50
bsize=25
k=floor(nu/bsize) # # of full blocks
reminder<-nu%%bsize # length of remaining incomplte block
reminder
listw_x_m<-make.w_x_(w=w,x=cbind(1,x),xm=cbind(1,xm),m=m,k=k,reminder =reminder)
startyu<-rep(0.1,nu)

tic()
mysamples<-sim_yugyotheta_(yo=yo,listw_x_m=listw_x_m,
                           yu.start=startyu,rc = ncol(x)+1,
                           paras=paras.st,N1=N1,k=k,bsize=bsize,reminder=reminder)

toc()

(mysamples$accepts)/((k+ifelse(reminder>0,1,0))*N1) # acceptance rate
dim((mysamples$yugyom.chain))
yu.start<-(mysamples$yugyom.chain)[N1,] # Select starting values of yu as the last value of the chain.
plot(yu,yu.start) #Plot: starting yu vs true yu 


#################################### Run Algorithms

# HVB-NoB
N=10000

tic()
fit_thetaAug_NoB<-MNAR_VB_thetaAug_NoB(x=x,xm=xm,m=m,w=w,
                                       yo=yo,startyu=yu.start,p=4,start_theta=paras.st,N=N,N1 = 10)   # N1 sets the no of MCMC saples
toc()

# HVB-AllB

bsize=floor(nu*0.25) # selecting block size to be nu*0.25
bsize.upall<-bsize

tic()
fit_thetaAug_update_all<-MNAR_VB_thetaAug_fullB_updating(x=x,xm=xm,m=m,
                                                         w=w,yo=yo,startyu=yu.start,p=4,
                                                         start_theta=paras.st,N=N,N1 = 10,bsize=bsize.upall) 
toc()


# HVB-3B (update 3 random blocks)


bsize.updateR3<-bsize
tic()
fit_thetaAug_updateR3<-MNAR_VB_thetaAug_R3B_updating(x=x,xm=xm,m=m,
                                                     w=w,yo=yo,startyu=yu.start,p=4,
                                                     start_theta=paras.st,N=N,N1 = 10,bsize=bsize.updateR3) 
toc()


#JVB

st=c(yu.start,paras.st)


tic()
fit_thetayu<-MNAR_thetayu(x=x,xm=xm,m=m,w=w,yo=yo,p=4,
                          start_theta=st,N=N)
toc()



#HMC
stan.data.list<-make.SATN.data(x=x,xm=xm,w=w,m=m,y=yo)
file.path="SEM_MNAR_HMC.stan"
iter=10000
tic()
fit_SEM_MNAR_HMC_thetayu<-stan(file = file.path,
                               data = stan.data.list,chains = 1,iter =iter) # default warm upsize=iter/2.
toc()

#Extract MCMC chains from HMC output
mcmc.chains.T<-as.matrix(fit_SEM_MNAR_HMC_thetayu)
HMC.thta.chains<-mcmc.chains.T[,(1:(ncol(mcmc.chains.T)-nu-1))]
yu.chains<-mcmc.chains.T[,-(1:(ncol(mcmc.chains.T)-nu-1))]
HMC.yu.chains<-yu.chains[,-(nu+1)]


###### Sample from posteriors of theta

# JVB




sample.size<-nrow(HMC.thta.chains)
yu.theta.sample<-matrix(rep(0,sample.size*(nparas+nu)),ncol = nparas+nu)

for(i in 1:sample.size){
  yu.theta.sample[i,]<-simulate_VB_yu.theta(mu=fit_thetayu$mu,x=x,
                                            B=fit_thetayu$B,
                                            d=fit_thetayu$d)
  
}

# HVB-NoB


theta.sample.NoB<-matrix(rep(0,sample.size*(nparas)),ncol = nparas)

for(i in 1:sample.size){
  theta.sample.NoB[i,]<-simulate_VB_theta(mu=fit_thetaAug_NoB$mu,
                                          B=fit_thetaAug_NoB$B,
                                          d=fit_thetaAug_NoB$d,
                                          x=x)
  
}

# HVB-AllB

theta.sample.upall<-matrix(rep(0,sample.size*(nparas)),ncol = nparas)

for(i in 1:sample.size){
  theta.sample.upall[i,]<-simulate_VB_theta(mu=fit_thetaAug_update_all$mu,
                                            B=fit_thetaAug_update_all$B,
                                            d=fit_thetaAug_update_all$d,
                                            x=x)
  
}

#HVB-3B

theta.sample.up3<-matrix(rep(0,sample.size*(nparas)),ncol = nparas)

for(i in 1:sample.size){
  theta.sample.up3[i,]<-simulate_VB_theta(mu=fit_thetaAug_updateR3$mu,
                                          B=fit_thetaAug_updateR3$B,
                                          d=fit_thetaAug_updateR3$d,
                                          x=x)
  
}




################ Generate density plots of theta


#1

# B0
name.list<-c("HMC","VB1","VB2-NoB","VB-upall","VB2-Up3B")

values=c("HMC"= "brown4","VB1"="blue","VB2-NoB"="green","VB-upall"="red","VB2-Up3B"="purple")





df <- data.frame(
  Group = rep(name.list, each = sample.size),
  Value = c(HMC.thta.chains[,"beta[1]"], yu.theta.sample[,(nu+1)],
            theta.sample.NoB[,(1)],theta.sample.upall[,1],theta.sample.up3[,1])
)

pp1 <- ggplot(df, aes(x = Value, color = Group)) +
  geom_density(fill = NA, size = 0.5) +
  theme_minimal() +
  scale_x_continuous(limits = c(0, 5)) +
  scale_y_continuous(limits = c(0, 3)) +
  scale_color_manual(values = values, breaks = c("HMC", "VB1","VB2-NoB","VB-upall","VB2-Up3B"),
                     labels = c("HMC", "JVB", "HVB-NoB","HVB-AllB","HVB-3B")) +  # Specify breaks
  labs(
    x = expression(beta[0]),
    y = "Density",
    color = "") +
  theme(
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.23, 0.82),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 22),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  ) +geom_vline(xintercept = para[1], linetype = "dashed", color = "orange")

pp1
# plot(x)
#beta3

df <- data.frame(
  Group = rep(name.list, each = sample.size),
  Value = c(HMC.thta.chains[,"beta[4]"], yu.theta.sample[,(nu+4)],
            theta.sample.NoB[,4],theta.sample.upall[,4],theta.sample.up3[,4])
)

ppb3 <- ggplot(df, aes(x = Value, color = Group)) +
  geom_density(fill = NA, size = 0.5,show.legend = FALSE) +
  theme_minimal() +
  scale_x_continuous(limits = c(0, 4.5)) +
  scale_y_continuous(limits = c(0, 7.7)) +
  scale_color_manual(values = values, breaks = c("HMC", "VB1","VB2-NoB","VB-upall","VB2-Up3B"),
                     labels = c("HMC", "VB1", "VB2-NoB","VB2-upallB","VB2-Up3B")) +
  labs(
    x = expression(beta[3]),
    y = "Density",
    color = "") +
  theme(
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.2, 0.86),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 22),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )+geom_vline(xintercept = para[4], linetype = "dashed", color = "orange")

ppb3



# sigma2y


hmc.sigma2y.smple<-exp(HMC.thta.chains[,"gama"])


df <- data.frame(
  Group = rep(name.list, each = sample.size),
  Value = c(hmc.sigma2y.smple, yu.theta.sample[,(nu+12)],
            theta.sample.NoB[,12],theta.sample.upall[,12],theta.sample.up3[,12])
)

pp2 <- ggplot(df, aes(x = Value, color = Group)) +
  geom_density(fill = NA, size = 0.5,show.legend = FALSE) +
  theme_minimal() +
  scale_x_continuous(limits = c(0, 4)) +
  scale_y_continuous(limits = c(0, 3.5)) +
  scale_color_manual(values = values, breaks = c("HMC", "VB1","VB2-NoB","VB-upall","VB2-Up3B"),
                     labels = c("HMC", "VB1", "VB2-NoB","VB2-upallB","VB2-Up3B")) +
  labs(
    x = expression(sigma[e]^2),
    y = "Density",
    color = "") +
  theme(
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.25, 0.72),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 22),  # Adjust the size as needed
    legend.text = element_text(size = 5))+geom_vline(xintercept = para[13], 
                                                     linetype = "dashed", color = "orange")

pp2



#rho

hmc.rho.smple<-((exp(HMC.thta.chains[,"lamda"]) -1)/(exp(HMC.thta.chains[,"lamda"]) +1))


df <- data.frame(
  Group = rep(name.list, each = sample.size),
  Value = c(hmc.rho.smple, yu.theta.sample[,(nu+13)],
            theta.sample.NoB[,13],theta.sample.upall[,13],theta.sample.up3[,13])
)

pp3 <- ggplot(df, aes(x = Value, color = Group)) +
  geom_density(fill = NA, size = 0.5,show.legend = FALSE) +
  theme_minimal() +
  scale_x_continuous(limits = c(-0.2, 1)) +
  scale_y_continuous(limits = c(0, 8.5)) +
  scale_color_manual(values = values, breaks = c("HMC", "VB1","VB2-NoB","VB-upall","VB2-Up3B"),
                     labels = c("HMC", "VB1", "VB2-NoB","VB2-upallB","VB2-Up3B")) +
  labs(
    x = expression(rho),
    y = "Density",
    color = "") +
  theme(
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.5, 0.72),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 22),  # Adjust the size as needed
    legend.text = element_text(size = 5))+geom_vline(xintercept = para[12], 
                                                     linetype = "dashed", color = "orange")

pp3


#psi0
df <- data.frame(
  Group = rep(name.list, each = sample.size),
  Value = c(HMC.thta.chains[,"psi[1]"], yu.theta.sample[,(nu+14)],
            theta.sample.NoB[,14],theta.sample.upall[,14],theta.sample.up3[,14])
)

pp4 <- ggplot(df, aes(x = Value, color = Group)) +
  geom_density(fill = NA, size = 0.5,show.legend = FALSE) +
  theme_minimal() +
  scale_x_continuous(limits = c(1, 2)) +
  scale_y_continuous(limits = c(0, 4)) +
  scale_color_manual(values = values, breaks = c("HMC", "VB1","VB2-NoB","VB-upall","VB2-Up3B"),
                     labels = c("HMC", "VB1", "VB2-NoB","VB2-upallB","VB2-Up3B")) +
  labs(
    x = expression(psi[0]),
    y = "Density",
    color = "") +
  theme(
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.25, 0.72),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 22),  # Adjust the size as needed
    legend.text = element_text(size = 5))+geom_vline(xintercept = psi[1], 
                                                     linetype = "dashed", color = "orange")

pp4

#psiy


df <- data.frame(
  Group = rep(name.list, each = sample.size),
  Value = c(HMC.thta.chains[,"psi[3]"], yu.theta.sample[,(nu+16)],
            theta.sample.NoB[,16],theta.sample.upall[,16],theta.sample.up3[,16])
)


pp5 <- ggplot(df, aes(x = Value, color = Group)) +
  geom_density(fill = NA, size = 0.5,show.legend = FALSE) +
  theme_minimal() +
  scale_x_continuous(limits = c(-0.25, 0)) +
  scale_y_continuous(limits = c(0, 41)) +
  scale_color_manual(values = values, breaks = c("HMC", "VB1","VB2-NoB","VB-upall","VB2-Up3B"),
                     labels = c("HMC", "VB1", "VB2-NoB","VB2-upallB","VB2-Up3B")) +
  labs(
    x = expression(psi[y]),
    y = "Density",
    color = "") +
  theme(
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.12, 0.72),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 22),  # Adjust the size as needed
    legend.text = element_text(size = 5))+geom_vline(xintercept = psi[3], 
                                                     linetype = "dashed", color = "orange")

pp5

# ?optim


pp=pp1+ppb3+pp2+pp3+pp4+pp5+plot_layout(ncol = 3,nrow = 2)

# ggsave(file = "kernal_SEM_MNAR_625_miss_75.png",
#        pp,width = 1350,height = 768,units = "px") 



########## missing values

####### Posterior mean and sd comparison of Missing values


#--- For HVB, we need to sample yu from its full conditional distribution.




N1=sample.size/2
bsize=50
k=floor(nu/bsize) # # of full blocks
reminder<-nu%%bsize # length of remaining incomplte block
listw_x_m<-make.w_x_(w=w,x=cbind(1,x),xm=cbind(1,xm),m=m,k=k,reminder =reminder)
# startyu<-rep(0.1,nu)

# Sample in HVB-NoB

tic()
yu_Aug_NoB<-sim_yugyotheta_(yo=yo,listw_x_m=listw_x_m,
                            yu.start=yu.start,rc = ncol(x)+1,
                            paras=apply(theta.sample.NoB,2,mean),N1=N1,k=k,bsize=bsize,reminder=reminder)

toc()


tic()
yu_Aug_all<-sim_yugyotheta_(yo=yo,listw_x_m=listw_x_m,
                            yu.start=yu.start,rc = ncol(x)+1,
                            paras=apply(theta.sample.upall,2,mean),N1=N1,k=k,bsize=bsize,reminder=reminder)

toc()


# Sample in HVB-3B
tic()
yu_Aug_3B<-sim_yugyotheta_(yo=yo,listw_x_m=listw_x_m,
                           yu.start=yu.start,rc = ncol(x)+1,
                           paras=apply(theta.sample.up3,2,mean),N1=N1,k=k,bsize=bsize,reminder=reminder)

toc()




## For VB1
# sample.size<-length(mcmc.chains.T$gama)
# yu.theta.sample<-matrix(rep(0,sample.size*(nparas+nu)),ncol = nparas+nu)
# 
# for(i in 1:sample.size){
#   yu.theta.sample[i,]<-simulate_VB_yu.theta(mu=fit_thetayu$mu,x=x,
#                                             B=fit_thetayu$B,
#                                             d=fit_thetayu$d)
#   
# }
# 


# VB's vs HMC Means
legend_labels<-c("JVB", "HVB-NoB","HVB-AllB","HVB-3B"
)

data <- data.frame(
  x = apply(HMC.yu.chains,2,mean),  # Replace with your x values
  vb1 = apply(yu.theta.sample[,1:nu],2,mean),  # Replace with your y values
  vb2NoB=apply((yu_Aug_NoB$yugyom.chain)[(N1/2):N1,],2,mean),
  vb2allup=apply((yu_Aug_all$yugyom.chain)[(N1/2):N1,],2,mean),
  vb23B=apply((yu_Aug_3B$yugyom.chain)[(N1/2):N1,],2,mean)
)


pp1 <- ggplot(data, aes(x = x)) +
  geom_point(aes(y = vb1, color = "vb1"), size = 2) +
  geom_point(aes(y = vb2NoB, color = "vb2NoB"), size = 2) + 
  geom_point(aes(y = vb2allup, color = "vb2allup"), size = 2) + 
  geom_point(aes(y = vb23B, color = "vb23B"), size = 2) + 
  labs(
    title = "",
    x = "HMC posterior means",
    y = "VB posterior means"
  ) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "green", "red"
                                ,"purple"), labels = legend_labels) +
  theme(
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    legend.position = c(0.25,0.8),  # Position the legend at the top of the plot
    panel.border = element_rect(color = "black", fill = NA, size = 1),  # Add a border around the plot
    
    axis.text = element_text(size = 22),  # Adjust the size as needed
    axis.title = element_text(size = 22),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5, size = 25),  # Adjust the size as needed
    legend.text = element_text(size = 22)  # Adjust the size as needed
  ) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "green") +
  guides(color = guide_legend(title = ""))  # legend title

pp1  # Display the plot
show(pp1)
# VB's vs HMC sd

# plot(apply(mcmc.chains.T$yu,2,sd),apply((yu_Aug_all$yugyom.chain)[5000:10000,],2,sd))
data <- data.frame(
  x = apply(HMC.yu.chains,2,sd),  # Replace with your x values
  vb1 = apply(yu.theta.sample[,1:nu],2,sd),  # Replace with your y values
  vb2NoB=apply((yu_Aug_NoB$yugyom.chain)[(N1/2):N1,],2,sd),
  vb2allup=apply((yu_Aug_all$yugyom.chain)[(N1/2):N1,],2,sd),
  vb23B=apply((yu_Aug_3B$yugyom.chain)[(N1/2):N1,],2,sd)
)

plot(apply(HMC.yu.chains,2,sd),apply((yu_Aug_NoB$yugyom.chain)[(N1/2):N1,],2,sd))
# plot(apply(mcmc.chains.T$yu,2,sd),apply((yu_Aug_all$yugyom.chain)[5000:10000,],2,sd))


pp2 <- ggplot(data, aes(x = x)) +
  geom_point(aes(y = vb1, color = "vb1"), size = 2) +
  geom_point(aes(y = vb2NoB, color = "vb2NoB"), size = 2) + 
  geom_point(aes(y = vb2allup, color = "vb2allup"), size = 2) + 
  geom_point(aes(y = vb23B, color = "vb23B"), size = 2) + 
  labs(
    title = "",
    x = "HMC posterior standard deviations",
    y = "VB posterior standard deviations"
  ) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "green", "red"
                                ,"purple"), labels = legend_labels) +
  theme(
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    legend.position = c(0.77,0.25),  # Position the legend at the top of the plot
    panel.border = element_rect(color = "black", fill = NA, size = 1),  # Add a border around the plot
    
    axis.text = element_text(size = 22),  # Adjust the size as needed
    axis.title = element_text(size = 22),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5, size = 25),  # Adjust the size as needed
    legend.text = element_text(size = 22)  # Adjust the size as needed
  ) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "green") +
  guides(color = guide_legend(title = ""))  # legend title
# scale_x_continuous(limits = c(0.9, 2.5)) +
# scale_y_continuous(limits = c(0.9, 2.5)) 

pp2  # Display the plot


# ggsave("C:/Users/61452/Desktop/P2-Simulations/SEM-MNAR/n_625/missing_75/MNAR_625_75p_vb_vs_HMC_mean.png",
#        plot = pp1, width = 11, height = 8)
# 
# ggsave("C:/Users/61452/Desktop/P2-Simulations/SEM-MNAR/n_625/missing_75/MNAR_625_75p_vb_vs_HMC_sd.png",
#        plot = pp2, width = 11, height = 8)
# nu

#################################### Final convergence plots




## VB1 JVB-lower bound


# Convert time series to dataframe
ts_data <- data.frame(Iteration = time(fit_thetayu$L.bound), 
                      Value = fit_thetayu$L.bound)

# Plot using ggplot2
pp.con.vb1=ggplot(ts_data, aes(x = Iteration, y = Value)) +
  geom_line(color = "blue",size = 0.25) +
  labs(x = "Iteration", y = "Lower bound of JVB")+
  theme(
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.29, 0.82),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 5),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )+ggtitle("JVB")

pp.con.vb1
####VB-2

# NoB

vb2.trojectry=(fit_thetaAug_NoB$all_paras)[,c(1,12,13,14)]
vb2.trojectry[,2]<-exp(vb2.trojectry[,2])
vb2.trojectry[,3]<-((exp(vb2.trojectry[,3]) -1)/(exp(vb2.trojectry[,3]) +1))
# vb1.trojectry[10000,]


vb2.trojectry<-as.data.frame(vb2.trojectry)
vb2.trojectry$Time<-1:10000
vb1.trojectry_melted <- melt(vb2.trojectry, id.vars = "Time")

legend_labels <- c(expression(beta[0]),
                   expression(sigma[e]^2), expression(rho), expression(psi[0]))

# Define line types
line_types <- c("solid", "dashed", "dotted", "dotdash")

pp.con.vbnob <- ggplot(data = vb1.trojectry_melted, aes(x = Time, y = value, color = variable, linetype = variable)) +
  geom_line(size = 0.25) +
  scale_color_manual(values = rep("green", length(legend_labels)), name = NULL, labels = legend_labels) +
  scale_linetype_manual(values = line_types, name = NULL, labels = legend_labels) + # Specify line types and remove linetype legend title
  labs(title = "",
       x = "Iteration", y = "Value") +
  theme_minimal() +
  theme(
    
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.2, 0.66),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 5),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )+ggtitle("HVB-NoB")

pp.con.vbnob




# all
vb2.trojectry=(fit_thetaAug_update_all$all_paras)[,c(1,12,13,14)]
vb2.trojectry[,2]<-exp(vb2.trojectry[,2])
vb2.trojectry[,3]<-((exp(vb2.trojectry[,3]) -1)/(exp(vb2.trojectry[,3]) +1))
# vb1.trojectry[10000,]


vb2.trojectry<-as.data.frame(vb2.trojectry)
vb2.trojectry$Time<-1:10000
vb1.trojectry_melted <- melt(vb2.trojectry, id.vars = "Time")


# Plot
# Plot
# Plot
# Plot


# Define legend labels
# Define legend labels
# Define legend labels
legend_labels <- c(expression(beta[0]),
                   expression(sigma[e]^2), expression(rho), expression(psi[0]))

# Define line types
line_types <- c("solid", "dashed", "dotted", "dotdash")

pp.con.vball <- ggplot(data = vb1.trojectry_melted, aes(x = Time, y = value, color = variable, linetype = variable)) +
  geom_line(size = 0.25) +
  scale_color_manual(values = rep("red", length(legend_labels)), name = NULL, labels = legend_labels) +
  scale_linetype_manual(values = line_types, name = NULL, labels = legend_labels) + # Specify line types and remove linetype legend title
  labs(title = "",
       x = "Iteration", y = "Value") +
  theme_minimal() +
  theme(
    
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.2, 0.66),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 5),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )+ggtitle("HVB-AllB")

pp.con.vball



# 3B


# all
vb2.trojectry=(fit_thetaAug_updateR3$all_paras)[,c(1,12,13,14)]
vb2.trojectry[,2]<-exp(vb2.trojectry[,2])
vb2.trojectry[,3]<-((exp(vb2.trojectry[,3]) -1)/(exp(vb2.trojectry[,3]) +1))


vb2.trojectry<-as.data.frame(vb2.trojectry)
vb2.trojectry$Time<-1:10000
vb1.trojectry_melted <- melt(vb2.trojectry, id.vars = "Time")


legend_labels <- c(expression(beta[0]),
                   expression(sigma[e]^2), expression(rho), expression(psi[0]))

# Define line types
line_types <- c("solid", "dashed", "dotted", "dotdash")

pp.con.vb3 <- ggplot(data = vb1.trojectry_melted, aes(x = Time, y = value, color = variable, linetype = variable)) +
  geom_line(size = 0.25) +
  scale_color_manual(values = rep("purple", length(legend_labels)), name = NULL, labels = legend_labels) +
  scale_linetype_manual(values = line_types, name = NULL, labels = legend_labels) + # Specify line types and remove linetype legend title
  labs(title = "",
       x = "Iteration", y = "Value") +
  theme_minimal() +
  theme(
    
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.2, 0.66),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 5),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )+ggtitle("HVB-3B")

pp.con.vb3


pp=pp.con.vb1+pp.con.vbnob+pp.con.vball+pp.con.vb3+plot_layout(ncol = 2,nrow = 2)


## HMC trace plots



beta0<-mcmc.chains.T[,"beta[1]"]
beta1<-mcmc.chains.T[,"beta[2]"]
gama<-mcmc.chains.T[,"gama"]
sigma2y<-exp(gama)
lamda<-mcmc.chains.T[,"lamda"]
rho<-((exp(lamda) -1)/(exp(lamda) +1))

###


beta0_df <- data.frame(
  Time = time(beta0),
  Value = as.numeric(beta0)
)

hmc.betao=ggplot(beta0_df, aes(x = Time, y = Value)) +
  geom_line(color="brown4") +
  labs(title = expression(beta[0]),
       x = "Iteration",
       y = "Value") +
  theme(
    
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.2, 0.8),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 5),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )



beta1_df <- data.frame(
  Time = time(beta1),
  Value = as.numeric(beta1)
)

hmc.beta1=ggplot(beta1_df, aes(x = Time, y = Value)) +
  geom_line(color="brown4") +
  labs(title = expression(beta[1]),
       x = "Iteration",
       y = "Value") +
  theme(
    
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.2, 0.8),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 5),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )


sigma2y_df <- data.frame(
  Time = time(sigma2y),
  Value = as.numeric(sigma2y)
)

hmc.sigma2y=ggplot(sigma2y_df, aes(x = Time, y = Value)) +
  geom_line(color="brown4") +
  labs(title = expression(sigma[e]^2),
       x = "Iteration",
       y = "Value") +
  theme(
    
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.2, 0.8),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 5),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )





rho_df <- data.frame(
  Time = time(rho),
  Value = as.numeric(rho)
)

hmc.rho=ggplot(rho_df, aes(x = Time, y = Value)) +
  geom_line(color="brown4") +
  labs(title = expression(rho),
       x = "Iteration",
       y = "Value") +
  theme(
    
    axis.line.x = element_line(color = "black", linewidth = 0.5),
    axis.line.y = element_line(color = "black", linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.2, 0.8),
    panel.border = element_blank(),
    panel.background = element_rect(color = "black", fill = NA, size = 0.5),
    
    axis.text = element_text(size = 5),  # Adjust the size as needed
    axis.title = element_text(size = 5),  # Adjust the size as needed
    plot.title = element_text(hjust = 0.5,size = 5),  # Adjust the size as needed
    legend.text = element_text(size = 5),  # Adjust the size as needed
    legend.key.size = unit(0.4, "lines"),
    legend.text.align = 0# Adjust the size as needed
  )



pp=hmc.betao+hmc.beta1+hmc.sigma2y+hmc.rho+plot_layout(ncol = 2,nrow = 2)













